config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show] 
  resources :events, only: [:new, :create, :show, :index] 
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :event_attended, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    has_many :attendances, foreign_key: "event_attended_id"
    has_many :event_attendeds, through: :attendances, source: :attendance

    has_many :invitations, foreign_key: "event_invite_id"
    has_many :coordinated_events, through: :invitations, source: :invitation

    validates :title, presence: true
    validates :datetime, presence: true

    scope :upcoming_events, -> { where("datetime > ?", Time.now) }
    scope :previous_events, -> { where("datetime < ?", Time.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :coordinated_events, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: "creator_id", class_name: "Event"

  has_many :attendances, foreign_key: "attendee_id", class_name: "Attendance"
  has_many :event_attendeds, through: :attendances

  has_many :invitations, foreign_key: "invitated_user_id", class_name: "Invitation"
  has_many :recipients, through: :invitations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    include EventsHelper
    before_action :authenticate_user!, only: [:new, :create]

    def index
        @events = Event.all
        @upcoming_events = @events.upcoming_events
        @previous_events = @events.previous_events
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.events.build(events_params)
        @event.save

        respond_to do |format|
            if @event.save
                format.html { redirect_to @event, notice: 'Event was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:current_user_id] = user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def events_params
        params.require(:event).permit(:title, :description, :datetime)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def users_params
        params.require(:user).permit(:username)
    end
end

app/views/events/index.html.erb
<% if user_signed_in? %>
    <%= link_to 'New Event', new_event_path, class: "button is-info is-inverted" %><br />
<% end %>

<h4>Upcoming Events In Your Area</h4>
<% @upcoming_events.each do |event| %>
    <br />
    <%= event.title %>
    <%= event.datetime %>
    <%= link_to "Details", event_path(event) %>
<% end %><br />

<h4>Previous Events In Your Area</h4>
<% @previous_events.each do |event| %>
    <br />
    <%= event.title %>
    <%= event.datetime %>
    <%= link_to "Details", event_path(event) %>
<% end %>

app/views/events/new.html.erb
<h1 class="title">Create a new Event</h1>

<%= form_for(@event, html: {multipart: true}) do |f| %>
    <ul>
        <% @event.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
    </ul>
    <%= f.text_field :title, label: "Write an event title", input_html: { class: "textarea" }, wrapper: false, label_html: {class: "label"}, autofocus: true %>
    <%= f.text_field :description, label: "Write an event description", input_html: { class: "textarea" }, wrapper: false, label_html: {class: "label"} %>
    <%= f.datetime_field :datetime, label: "Write an event time", input_html: { class: "textarea" }, wrapper: false, label_html: {class: "label"} %>
    <%= f.button :submit, class: "button is-info" %>
<% end %>

<%= link_to 'Cancel', events_path, class: "button is-dark" %>

app/views/events/show.html.erb
<%= @event.title %><br />
<p>Organizer:<br>
  <%= link_to "#{@event.creator.username}", user_path(@event.creator_id) %>
</p>
<%= @event.description %><br />
<%= @event.datetime %><br />

<!--
<h2>Click to RSVP for this event!</h2><br />
<form>
    <%= link_to "RSVP", events_path, :class => 'btn btn-primary'%>
</form>
-->

<h3>Currently <%= @event.attendances.count %> people attending: </h3>
<ul>
    <% @event.attendances.each do |attendance| %>
        <li><%= attendance.username %></li>
    <% end %>
</ul>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:notice]%>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <h6>
        <% if user_signed_in? %>
            <%= "Logged in as #{current_user.username}" %><br />
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
        <% else %>
            <p class="control">
                <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
            <p class="control">
                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
        <% end %>
    </h6>

    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h4>Events This User Is Attending</h4>
<% @user.events.each do |event| %>
    <%= link_to event.title, event_path(event) %><br />
    <%= event.description %><br />
    <%= event.datetime %><br />
<% end %>

<%= link_to 'Back', events_path %>